CREATE DATABASE propellerhead;
CREATE TABLE customers(id INTEGER PRIMARY KEY AUTO_INCREMENT, status INTEGER, created DATETIME, name VARCHAR(128), details VARCHAR(128));
CREATE TABLE notes(id INTEGER PRIMARY KEY AUTO_INCREMENT, note VARCHAR(256), modified DATETIME, customerID INTEGER, FOREIGN KEY(customerID) REFERENCES customers(id));